server:
  port: 8001
spring:
  application:
    name: generator-service
  profiles: one
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---

server:
  port: 8002
spring:
  application:
    name: generator-service
  profiles: two
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

