server:
  port: 8002
spring:
  application:
    name: generator-service
  zipkin:
      base-url: http://localhost:9103
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/