server:
  port: 9101
spring:
  application:
    name: gateway
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
#    generator:
#      path: /generator/**
#      serviceId: generator-service
    baseService:
      path: /base/**
      serviceId: base-service
    businessService:
          path: /business/**
          serviceId: business-service
    wxService:
              path: /wx/**
              serviceId: wx-service
management:
  security:
    enabled: false