server:
  port: 9101
spring:
  rabbitmq:
      host: 39.105.100.16
      port: 5672
      username: weight
      password: weight
#  application:
#    name: gateway
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
#    generator:
#      path: /generator/**
#      serviceId: generator-service
    baseService:
      path: /base/**
      serviceId: base-service
    businessService:
          path: /business/**
          serviceId: business-service
    wxService:
              path: /wx/**
              serviceId: wx-service
#    baidu:
#      url: https://www.baidu.com
management:
  security:
    enabled: false