server:
  port: 8801
spring:
  application:
    name: base-service
  datasource:
    url: jdbc:mysql://localhost/weight_base?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password:
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
mybatis:
  type-aliases-package: cn.liangyt.base.mapper
  mapper-locations: mybatis/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
custom:
  info:
    idc: 0
    machineId: 0
