server:
  port: 7001
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config-server
  rabbitmq:
        host: 39.105.100.16
        port: 5672
        username: weight
        password: weight
  cloud:
    config:
      server:
        git:
          uri: http://git.liangyongtong.cn/r/weight.git
          search-paths: '{application}'
          username: lyt
          password: 123456
management:
  security:
    enabled: false # 关闭安全认证